export function setupArchiveTools({root,r,user,api,esc,openModal,notify,refresh}){
 if(user?.role!=='admin')return;
 const tools=document.createElement('div');tools.className='feature-toolbar';root.append(tools);
 const button=(text,run)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=async()=>{b.disabled=true;try{await run();}catch(e){notify(e.message,'error');}finally{b.disabled=false;}};tools.append(b);};
 if(r.view==='admin'){
  button('Vận hành',async()=>{const d=await api('/admin/operations');openModal(`<h2 id="modal-title">Vận hành</h2><p>${esc(d.at)} · Làm mới bằng cách mở lại bảng.</p><ul><li>Game thêm/phút: ${d.uploads_minute}</li><li>Boot queue: ${d.boot_queued} chờ · ${d.boot_running} đang chạy</li><li>JAR theo DB: ${(d.jar_bytes/1048576).toFixed(1)} MB</li><li>Cloud Save từng game: ${(d.cloud_bytes/1048576).toFixed(1)} MB</li><li>DB round trip: ${d.db_ms} ms</li><li>Socket relay đang hoạt động: ${d.relay_sockets}</li>${['api_errors','rate_limited','relay_rejected'].map(k=>`<li>${{api_errors:'API 5xx',rate_limited:'Rate limit HTTP',relay_rejected:'Endpoint bị từ chối'}[k]} trong giờ qua: ${esc(d.events.find(e=>e.kind===k)?.hits||0)}</li>`).join('')}</ul><p>Dung lượng dựa trên bản ghi DB, chưa bao gồm object mồ côi hoặc media. Socket từ heartbeat máy chủ relay trong 90 giây; Vercel không chạy relay WebSocket. Chỉ tính sự kiện kể từ khi triển khai đo đạc.</p>`);});
  button('Lỗi emulator',async()=>{const rows=await api('/admin/telemetry');openModal(`<h2 id="modal-title">Lỗi emulator · 30 ngày</h2><p>Metadata do người chơi đồng ý gửi; không chứa nội dung lỗi, chat hoặc stack thô. Số liệu chưa xác minh, không dùng để kết luận game hỏng.</p>${rows.map(x=>`<article class="review"><strong>${esc(x.exception)}</strong><p>${x.occurrences} lần · ${x.versions} SHA256</p><p>${esc(x.runtime)} · ${esc(x.last_seen)}</p><code style="overflow-wrap:anywhere">${esc(x.signature)}</code></article>`).join('')||'<p>Chưa có báo cáo.</p>'}`);});
 }
 if(r.view==='game')button('Đối chiếu metadata',async()=>{
  const d=await api(`/admin/games/${r.id}/metadata`),names={title:'Tên game',publisher:'Nhà phát hành',developer:'Nhà phát triển',release_year:'Năm',language:'Ngôn ngữ',country:'Quốc gia',network_mode:'Chế độ mạng'};
  openModal(`<h2 id="modal-title">Đối chiếu metadata</h2><p>Chỉ trường bạn chọn mới được cập nhật và đánh dấu đã xác minh. Chọn nguồn khác sẽ thay giá trị đã xác minh.</p><form id="reconcile-form" class="stack">${Object.entries(d.fields).map(([k,v])=>`<label>${names[k]} ${v.verified?'✓ Đã xác minh':''}<select name="${k}"><option value="">Không thay đổi</option>${['current','source','manifest'].filter(origin=>v[origin]!=null&&v[origin]!=='').map(origin=>`<option value="${origin}">${{current:'Hiện tại',source:'Nguồn',manifest:'Manifest'}[origin]}: ${esc(v[origin])}</option>`).join('')}</select></label>`).join('')}<p role="alert"></p><button>Xác nhận lựa chọn</button></form>`);
  const form=document.getElementById('reconcile-form');form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;try{const choices=Object.fromEntries([...new FormData(form)].filter(([,v])=>v));await api(`/admin/games/${r.id}/metadata`,{method:'PUT',body:{revision:d.revision,choices}});document.querySelector('#modal').close();await refresh();}catch(error){form.querySelector('[role=alert]').textContent=error.message;}finally{b.disabled=false;}};
 });
}
