const collections=[['teamobi','Game TeaMobi'],['java240','Java 240×320'],['offline','Game Offline'],['online','Game Online'],['rpg','RPG Java'],['vietnam','Game Việt Nam'],['nostalgia','Game tuổi thơ'],['new','Game vừa thêm']];
export function smartCollections(esc,selected) {
    return `<details class="catalog-discovery" ${selected?'open':''}><summary>Bộ sưu tập thông minh</summary><nav aria-label="Bộ sưu tập thông minh">${collections.map(([id,title])=>`<a class="button small" href="/games?smart=${id}" ${selected===id?'aria-current="page"':''}>${esc(title)}</a>`).join('')}<a class="button small" href="/history">Chơi gần đây</a></nav><p class="muted">Theo dữ liệu đã xác nhận; “tuổi thơ” do người quản lý chọn. Game vừa thêm: 30 ngày gần nhất.</p></details>`;
}
export function advancedFilters(q,esc) {
    const select=(name,title,values)=>`<label>${title}<select name="${name}"><option value="">Tất cả</option>${values.map(([value,label])=>`<option value="${value}" ${q.get(name)===value?'selected':''}>${label}</option>`).join('')}</select></label>`;
    const text=(name,title,type='text',extra='')=>`<label>${title}<input name="${name}" type="${type}" value="${esc(q.get(name))}" ${extra}></label>`;
    return `${q.has('smart')?`<input type="hidden" name="smart" value="${esc(q.get('smart'))}">`:''}<details class="advanced-catalog" ${['developer','year','language','network','touch','min_size','max_size','compatibility','country'].some(k=>q.get(k))?'open':''}><summary>Bộ lọc nâng cao</summary><div>${text('developer','Nhà phát triển','text','maxlength="100"')}${text('year','Năm phát hành','number','min="1980" max="2100"')}${text('language','Ngôn ngữ (ví dụ: vi, en)','text','maxlength="100"')}${text('country','Quốc gia (ví dụ: VN)','text','maxlength="100"')}${select('network','Kết nối',[['online','Online'],['offline','Offline'],['unknown','Chưa rõ']])}${select('touch','Điều khiển',[['true','Có cảm ứng'],['false','Phím, không cảm ứng'],['unknown','Chưa rõ']])}${text('min_size','Dung lượng từ (byte)','number','min="0" max="20971520"')}${text('max_size','Dung lượng đến (byte)','number','min="0" max="20971520"')}${select('compatibility','Có phản hồi tương thích',[['works','Chơi tốt'],['graphics','Lỗi hình'],['network','Lỗi mạng'],['startup','Không khởi động']])}</div><p class="muted">Thông tin chưa rõ không được xem là Offline hoặc không hỗ trợ cảm ứng.</p><button>Áp dụng bộ lọc</button> <a href="/games">Xóa bộ lọc</a></details>`;
}
export function metadataEditor(game,esc) {
    const text=(name,title,type='text')=>`<label>${title}<input name="${name}" type="${type}" ${type==='number'?'min="1980" max="2100"':'maxlength="100"'} value="${esc(game[name])}"></label>`;
    return `<details><summary>Thông tin tìm kiếm &amp; bộ sưu tập</summary><div class="stack">${text('publisher','Nhà phát hành')}${text('developer','Nhà phát triển')}${text('release_year','Năm phát hành','number')}${text('language','Ngôn ngữ (vi, en…)')}${text('country','Quốc gia (VN…)')}<label>Kết nối<select name="network_mode"><option value="">Chưa rõ</option><option value="online" ${game.network_mode==='online'?'selected':''}>Online</option><option value="offline" ${game.network_mode==='offline'?'selected':''}>Offline</option></select></label><label>Bộ sưu tập tuổi thơ<select name="nostalgic"><option value="false">Không</option><option value="true" ${game.nostalgic?'selected':''}>Có</option></select></label></div></details>`;
}
export function progressProfile(progress,esc) {
    if(!progress)return '';
    const unlocked=progress.achievements.filter(a=>a.unlocked);
    return `<section class="profile-progress"><h2>Hành trình Java</h2><p><strong>${progress.games}</strong> game · <strong>${(progress.seconds/3600).toFixed(1)}h</strong> chơi · <strong>${unlocked.length}</strong> thành tích</p><ul>${progress.achievements.map(a=>`<li>${a.unlocked?'🏆':'○'} ${esc(a.title)}${a.unlocked?'':' — chưa đạt'}</li>`).join('')}</ul><p class="muted">Thời gian từ khi bật tính năng, chỉ tính tab game đang hiển thị. Hồ sơ công khai chỉ thống kê game công khai.</p>${progress.completed.length?`<h3>Đã hoàn thành — người chơi tự xác nhận</h3><ul>${progress.completed.map(g=>`<li>${esc(g.title)}</li>`).join('')}</ul>`:''}</section>`;
}
